version: '3'

volumes:
  keycloak_data:
    driver: local
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8080:8080
    depends_on:
      - postgres
  db:
    image: postgres
    container_name: learn_express_postgres
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=pwd0123456789
    ports:
      - 54320:5432
    #   Set a volume some that database is not lost after shutting down the container.
    #   I used the name postgres-data but you can changed it to something else.
    # On Windows must use .env COMPOSE_CONVERT_WINDOWS_PATHS=true
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    # command: sleep infinity